name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: hsptest_test以下を全てテスト
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: cache HSP3.6
        id: cache-hsp36
        uses: actions/cache@v3
        with:
          path: C:/hsp36
          key: ${{ runner.os }}-hsp36
          restore-keys: |
            ${{ runner.os }}-hsp36

      - name: download HSP3.6
        if: ${{ steps.cache-hsp36.outputs.cache-hit != 'true' }}
        uses: robinraju/release-downloader@v1.4
        with:
          repository: "onitama/OpenHSP"
          tag: "v3.6"
          fileName: "hsp36en.zip"

      - name: unzip hsp36en.zip
        if: ${{ steps.cache-hsp36.outputs.cache-hit != 'true' }}
        run: 7z x hsp36en.zip -oC:/

      - name: compile and install hsptest
        shell: cmd
        run: |
          echo "C:/hsp36" >> %GITHUB_PATH%
          hspcmp -o"compile.ax" --compath="C:/hsp36/common" ./compile.hsp
          hsp3cl compile.ax
          echo | call install.bat

      - name: test
        shell: pwsh
        run: |
          echo "C:/hsp36" >> $env:GITHUB_PATH
          hsptest -v -s hsptest_test
