name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: hsptest_test以下を全てテスト
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: cache HSP3.7
        id: cache-hsp37
        uses: actions/cache@v3
        with:
          path: C:/hsp37
          key: ${{ runner.os }}-hsp37
          restore-keys: |
            ${{ runner.os }}-hsp37

      - name: download HSP3.7
        if: ${{ steps.cache-hsp37.outputs.cache-hit != 'true' }}
        uses: robinraju/release-downloader@v1.4
        with:
          repository: "onitama/OpenHSP"
          tag: "v3.7"
          fileName: "hsp37en.zip"

      - name: unzip hsp37en.zip
        if: ${{ steps.cache-hsp37.outputs.cache-hit != 'true' }}
        run: 7z x hsp37en.zip -oC:/

      - name: add hsp37 to path
        shell: pwsh
        run: echo "C:/hsp37" >> $env:GITHUB_PATH

      - name: compile and install hsptest
        shell: pwsh
        run: |
          hspcmp -o"compile.ax" --compath="C:/hsp37/common" ./compile.hsp
          cp common/* C:/hsp37/common/
          hsp3cl compile.ax
          cp hsptest.exe C:/hsp37/

      - name: test
        shell: pwsh
        run: |
          hsptest -v -s hsptest_test
